---
title: "Fig5_S9~S11"
author: "Boyan Zhou"
data: "12-03-2025"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r library, message=FALSE, include=FALSE}
library(dplyr)
library(ggpubr)
library(ggvenn)
library(ggplot2)
library(tidyr)
library(phyloseq)
require(ggsci)
require(vegan)
require(ANCOMBC)
library(EnhancedVolcano)
library("ggalluvial")
library("RColorBrewer")
library(tibble)

```

# Fig. 5a & Fig. S9
```{r community contribution, warning=FALSE, eval=FALSE, include=FALSE}

contribution_liu_plot_list <- NULL
test_p_list <- NULL 
contribution_res_table_list <- NULL

target_gene_list
for(i in target_gene_list) {
  gene_name <- strsplit(i, split = "_")[[1]][1]
  info_vec <- strsplit(i, split = "_")[[1]]
  lookup <- c(dna = "MGX", rna = "MTX")
  data_type <- lookup[info_vec[2]]

  phylo_obj_temp <- phylo_obj_list[[paste(i, "PAIRED", sep="_")]]
  phylo_obj_temp <- tax_glom(phylo_obj_temp, "genus")
  # tax_table(phylo_obj_temp)
  otu_temp <- data.frame(otu_table(phylo_obj_temp))
  tax_temp <- data.frame(tax_table(phylo_obj_temp))
  rownames(otu_temp) <- tax_temp$genus
  metadata_temp <- sample_data(phylo_obj_temp)
  
  # calculate Cij
  otu_ra_temp <- sweep(otu_temp, 2, colSums(otu_temp), FUN = "/")
  otu_temp_dna <- otu_ra_temp[, which(metadata_temp$nucleic_acid == "dna")]

  otu_temp_dna[is.na(otu_temp_dna)] <- 0
  otu_temp_rna <- otu_ra_temp[, which(metadata_temp$nucleic_acid == "rna")]

  otu_temp_rna[is.na(otu_temp_rna)] <- 0

  
  pop_contribution <- data.frame(MGX = rowSums(otu_temp_dna)/sum(rowSums(otu_temp_dna)), 
                                 MTX = rowSums(otu_temp_rna)/sum(rowSums(otu_temp_rna)))
  contribution_res_table_list[[i]] <- pop_contribution

  species_dna_top10 <- rownames(pop_contribution)[order(pop_contribution[["MGX"]], 
                                                        decreasing = T)[1:10]]
  species_rna_top10 <- rownames(pop_contribution)[order(pop_contribution[["MTX"]], 
                                                        decreasing = T)[1:10]]
  species_rna_top10_overlap <- unique(c(species_dna_top10, species_rna_top10))

  pop_contribution_reduced <- pop_contribution[rownames(pop_contribution) %in% species_rna_top10_overlap,]
  Others <- 1 - colSums(pop_contribution_reduced)
  pop_contribution_reduced <- rbind(pop_contribution_reduced, Others)
  rownames(pop_contribution_reduced)[nrow(pop_contribution_reduced)] <- "Others"
  
  pop_contribution_reduced_trans <- data.frame(data_type = rep(c("MGX", "MTX"),
                                                               c(nrow(pop_contribution_reduced), nrow(pop_contribution_reduced))), 
                                               species = rep(rownames(pop_contribution_reduced),2),
                                               contribution = c(pop_contribution_reduced[["MGX"]], pop_contribution_reduced[["MTX"]]))
  
  pop_contribution_reduced_trans$species <- factor(pop_contribution_reduced_trans$species, levels = rownames(pop_contribution_reduced))

  plot_temp <- ggplot(pop_contribution_reduced_trans, aes(x = data_type, y = contribution, alluvium = species)) + 
	geom_alluvium(aes(fill = species), colour = "black", alpha = 1, decreasing = F) + 
	labs(x = "", y = "Proportion", fill = "", colour = "", title=bquote("Population-level genus contributions to " * italic(.(gene_name)))) + 
	scale_x_discrete(expand = c(0.02,0.02)) + 
	theme(legend.position = "right", axis.text.y = element_text(colour = "black", size = 12, face = "bold"), 
	axis.text.x = element_text(colour = "black", face = "bold", angle =0, size = 12, vjust = 0.5), 
	axis.title.y = element_text(colour = "black", face = "bold", size = 14), 
	panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2), 
	legend.text = element_text(size = 10, face = "italic")) + 
	scale_fill_manual(values = nature_palette)
  
  # save plot in list
  contribution_liu_plot_list[[i]] <- plot_temp
}

#########
# Fig5a #
#########
ggsave(
  filename = "fig5a.pdf",
  plot     = contribution_liu_plot_list[["ygeX"]],
  width    = 6, 
  height   = 6, 
  units    = "in", 
  dpi      = 500,
  device   = "pdf"
)
names(contribution_liu_plot_list)

###########
# Fig.S9 #
###########
figS9 <- ggarrange(contribution_liu_plot_list[["hyuA"]],
                   contribution_liu_plot_list[["ssnA"]],
                   contribution_liu_plot_list[["xdhA"]],
                   contribution_liu_plot_list[["ygeY"]],
                   contribution_liu_plot_list[["ygeW"]],
                   contribution_liu_plot_list[["ygfK"]],
                   ncol = 3, nrow = 2, 
                   labels = c("a", "b", "c", "d", "e", "f"))
ggsave(
  filename = "figS9.jpg",
  plot     = figS9,
  width    = 18, 
  height   = 12, 
  units    = "in", 
  dpi      = 500,
  device   = "jpg"
)

```


# Fig. 5b
```{r community contribution, warning=FALSE, eval=FALSE, include=FALSE}
library(ComplexHeatmap)
library(circlize)
library(ggplot2)
library(reshape2)
library(RColorBrewer)
library(Hmisc)


bubble_cor <- ggplot(cor_long, aes(x = Var2, y = Var1)) +
  geom_point(aes(size = size, fill = value), shape = 21, color = "black") +
  geom_tile(fill = NA, color = "black", width = 1, height = 1) +
  geom_text(aes(label = signif), size = 3, vjust = 0.5, hjust = 0.5) +
  scale_fill_gradient2(low = "#2166AC", mid = "white", high = "#B2182B", midpoint = 0) +
  scale_size(range = c(3, 10)) +
  theme_minimal(base_size = 11) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 9, face = "bold"),
    axis.text.y = element_text(size = 9, face = "italic"),   # y轴斜体
    axis.title = element_blank(),
    panel.grid = element_blank(),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 9)
  ) +
  labs(fill = "Pearson r", size = "|r|") +
  coord_fixed()

ggsave(
  filename = "fig5b.pdf",
  plot     = bubble_cor,
  width    = 6, 
  height   = 6, 
  units    = "in", 
  dpi      = 500,
  device   = "pdf"
)
```


# Fig5. c-d & Fig. S11
```{r, eval=FALSE, include=FALSE}
library(pheatmap)


gene_heatp <- pheatmap(mat,
         color = colorRampPalette(c("#2166AC", "white", "#B2182B"))(100),
         border_color = NA,
         fontsize = 10,
         fontsize_row = 8,
         fontsize_col = 9,
         angle_col = 45,
         na_col = "grey90",
         cluster_rows = FALSE,          # disable row clustering
         cluster_cols = FALSE,
         )

  ggsave(
  filename = "heatmap_across_genes.jpg",
  plot     = gene_heatp,
  width    = 10, 
  height   = 10, 
  units    = "in", 
  dpi      = 500,
  device   = "jpg"
)
  

#########
# fig5d #
#########
gene_heatp_filtered <- pheatmap(mat_filtered,
         color = colorRampPalette(c("#2166AC", "white", "#B2182B"))(100),
         border_color = NA,
         fontsize = 10,
         fontsize_row = 8,
         fontsize_col = 9,
         angle_col = 45,
         na_col = "grey90",
         cluster_rows = FALSE,          # disable row clustering
         cluster_cols = FALSE,
         display_numbers = sig_stars,
         number_color = "black",
         labels_row = parse(text = rownames(mat_filtered))
         )



  ggsave(
  filename = "fig5d.pdf",
  plot     = gene_heatp_filtered,
  width    = 5, 
  height   = 5, 
  units    = "in", 
  dpi      = 500,
  device   = "pdf"
)
  
#---------------------------------------------------------------------------------------------
################
# volcano plot #
################
# Fig5c
#  Fig. S11 | Associations between species-level abundances of six urate-degradation genes and animal-protein intake.
  

target_gene_list
for(i in target_gene_list) {
  j = paste(i, "PAIRED", "dna",sep = "_")
  xxx_sens <- ancombc_res_aprot10a_species_list[[j]]$pseudo_sens_tab
  xxx_res <- ancombc_res_aprot10a_species_list[[j]]$res
  xxx_robust_res <- xxx_res[xxx_sens$aprot10a <=0.1,]
  
  species_volcano_robust_p <- EnhancedVolcano(xxx_robust_res, 
                            lab = xxx_robust_res$taxon,
                            x = 'lfc_aprot10a', y = 'p_aprot10a',
                            title = NULL,
                            subtitle =bquote(Associations~between~italic(.(i))~abundance~and~animal~protein),
                            xlab = "Log2 fold change", 
                            ylim = c(0, 3),
                            xlim = c(-0.1, 0.1),
                            pCutoff = 0.1,
                            FCcutoff = 0.02,
                            pointSize =2,
                            caption = NULL,
                            labSize = 4.0)
  # aprot_volcano_plot_list[[i]] <- species_volcano_p 
  aprot_volcano_plot_robust_list[[i]] <- species_volcano_robust_p
}

############
# fig. S11 #
############
names(aprot_volcano_plot_robust_list)

figs11 <- ggarrange(aprot_volcano_plot_robust_list[["hyuA"]], 
          aprot_volcano_plot_robust_list[["ssnA"]],
          aprot_volcano_plot_robust_list[["xdhA"]], 
          aprot_volcano_plot_robust_list[["ygeY"]],
          aprot_volcano_plot_robust_list[["ygeW"]], 
          aprot_volcano_plot_robust_list[["ygfK"]],
          ncol=3, nrow = 2, common.legend = T,
          legend = "right", labels = c("a", "b", "c", "d", "e", "f"))

ggsave(
  filename = "figs11_1208.jpg",
  plot     = figs11,
  width    = 26, 
  height   = 16, 
  units    = "in", 
  dpi      = 500,
  device   = "jpg"
)


############
# fig. 5c #
############
i = "ygeX"
  j = paste(i, "PAIRED", "dna",sep = "_")
  xxx_sens <- ancombc_res_aprot10a_species_list[[j]]$pseudo_sens_tab
  xxx_res <- ancombc_res_aprot10a_species_list[[j]]$res
  xxx_robust_res <- xxx_res[xxx_sens$aprot10a <=0.1,]
  
  fig5c <- EnhancedVolcano(xxx_robust_res, 
                            lab = "",
                            # lab = xxx_robust_res$taxon,
                            x = 'lfc_aprot10a', y = 'p_aprot10a',
                            title = NULL,
                            subtitle =bquote(Associations~between~italic(.(i))~abundance~and~animal~protein),
                            xlab = "Log2 fold change", 
                            ylim = c(0, 3),
                            xlim = c(-0.1, 0.1),
                            pCutoff = 0.1,
                            FCcutoff = 0.02,
                            pointSize =2,
                            caption = NULL,
                            labSize = 4.0)
  

ggsave(
  filename = "fig5c.pdf",
  plot     = fig5c,
  width    = 6, 
  height   = 6, 
  units    = "in", 
  dpi      = 500,
  device   = "pdf"
)




```



# Fig. S10 
```{r, eval=FALSE, include=FALSE}
aprot_fruct_p <- ggscatter(meta_MLVS_merged, x ="aprot10a", y = "fruct10a",
               color = "#4C4C4C",        
               size = 2.2, 
               shape = 16,
               alpha = 0.85,             
               add = "reg.line",        
               add.params = list(color = "#0072B2", size = 0.8),  
               conf.int = TRUE) +
  stat_cor(method = "pearson") +
  theme_classic(base_size = 14) +
  labs(x = "Animal protein (g/day)",
       y = "Fructose (g/day)")

  ggsave(
  filename = "Fig_S10_.jpg",
  plot     = aprot_fruct_p,
  width    = 5, 
  height   = 5, 
  units    = "in", 
  dpi      = 500,
  device   = "jpg"
)
```








