import os
import json
import pandas as pd
import subprocess
import log_setup
import argparse
import summarize_contribution


def get_args():
    """Parses command-line arguments and returns them."""

    # Define parent parser for shared arguments
    parent_parser = argparse.ArgumentParser(add_help=False)
    parent_parser.add_argument("-g", "--gene-prefix", type=str, required=True, help="Prefix for gene files")
    parent_parser.add_argument("-o", "--output-dir", type=str, required=True, help="Directory of output ")
    parent_parser.add_argument("-L", "--logger-path", type=str, required=True, help="Path to save log files")

    # Main parser
    parser = argparse.ArgumentParser(description="Build diamond_db, align sequence by diamond, and summarize.")
    subparsers = parser.add_subparsers(dest="mode", help="Mode of operation")
    #########################################
    # Subparser for build 'diamond_db' mode #
    #########################################
    parser_diamond = subparsers.add_parser("build_diamond_db", parents=[parent_parser],
                                           help="Build the diamond database for target gene "
                                                "by core Uniref100 and sponge sequences.")
    parser_diamond.add_argument("-c", "--core-rep-uniref100", type=str, required=True,
                                help="Path to the core representative UniRef100 "
                                     "generated by 'recluster_species_UniRef.py'.")
    parser_diamond.add_argument("-s", "--sponge-fas-path", type=str,
                                help="Path to the FASTA file of sponge Sequence, "
                                     "generated by 'refine_core_UniRef90s.py'.")
    parser_diamond.add_argument("--uniprotkb-dir", type=str,
                                help="Path to the directory of UniProtKB generated by 'construct_database.py'.")
    ##################################################
    # Subparser for 'align' sequence by diamond mode #
    ##################################################
    parser_align = subparsers.add_parser("align", parents=[parent_parser],
                                         help="Align raw sequence to finalized database by "
                                              "'build_diamond_db' in last step.")
    parser_align.add_argument("-d", "--diamond-db", type=str, required=True,
                              help="Path to the diamond database (.dmnd) built in last step by 'build_diamond_db'")
    parser_align.add_argument("--sample-fastq", type=str,
                              help="For multiple samples: not used together with --sample, --fastq \n"
                                   "Path to the csv table (separated by ',') containing sample information. "
                                   "The first column is the sample ID and the second column is the path to fq or "
                                   "fq.gz. For paired-end sample, the path to R1 and the path to R2 should be "
                                   "separated by ':' within the second column (PATH/XXX_R1.fq:PATH/XXX_R2.fq).")
    parser_align.add_argument("--sample", type=str, help="For single sample, sample ID.")
    parser_align.add_argument("--fastq", type=str,
                              help="For single sample, path to the fq or fq.gz. \n"
                                   "For paired-end sample, path to R1 and R2 should be separated by ':', "
                                   "like (PATH/XXX_R1.fq:PATH/XXX_R2.fq)")
    parser_align.add_argument("--thread", type=int, default=4, help="Number of thread for diamond align.")
    parser_align.add_argument("--max-hit", type=int, default=10, help="Number of max target seqs per query in diamond.")
    parser_align.add_argument("--identity-threshold", type=int, default=85,
                              help="Threshold of alignment identity (0~100).")
    parser_align.add_argument("--query-coverage", type=int, default=85,
                              help="Threshold of query covered percentage (0~100).")
    ######################################################
    # Subparser for 'summarize' sequence by diamond mode #
    ######################################################
    parser_summarize = subparsers.add_parser("summarize", parents=[parent_parser],
                                             help="Summarize the count/RPKM/CPM data from diamond reports.")
    parser_summarize.add_argument("--read-count", type=str, required=True,
                                  help="Filename of reads count file for fastq. For example, the name of the "
                                       "dataset + sequencing type (XXX_study_MGX_read_count.tsv).")
    parser_summarize.add_argument("--sample-fastq", type=str, required=True,
                                  help="For multiple samples: not used together with --sample, --fastq \n"
                                  "Path to the csv table (separated by ',') containing sample information. "
                                  "The first column is the sample ID and the second column is the path to fq or "
                                  "fq.gz. For paired-end sample, the path to R1 and the path to R2 should be "
                                  "separated by ':' within the second column (PATH/XXX_R1.fq:PATH/XXX_R2.fq).")

    parser_summarize.add_argument("--sample-diamond", type=str, required=True,
                                  help="Path to the csv table (separated by ',') containing sample and corresponding "
                                       "diamond report. The first column is the sample ID and the second column is "
                                       "the path to its corresponding diamond report. For paired-end sample, "
                                       "the path to R1 report and the path to R2 report should be separated by ':' "
                                       "within the second column (PATH/XXX_R1_diamond.output:PATH/XXX_R2_diamond."
                                       "output).")
    parser_summarize.add_argument("--tax-mapping", type=str, required=True,
                                  help="Path to the csv file of correspondence between taxonomy and finalized uniref100.")
    parser_summarize.add_argument("--identity-threshold", type=int, default=70,
                              help="Threshold of alignment identity (0~100).")
    parser_summarize.add_argument("--len-threshold", type=int, default=30,
                              help="Threshold of length of aligned amino acids threshold.")
    args1 = parser.parse_args()

    if args1.mode is None:
        parser.error("A sub-command is required. Use -h for help.")
    return args1


if __name__ == "__main__":
    args = get_args()
    logger = log_setup.setup_log_file(args.logger_path)
    # uniref_species = UniRefSpecies(args.uniref_taxonomy_path, args.uniref100_fas_path, logger)
    if args.mode == "build_diamond_db":
        """
        Example:
        echo "$gene"
        gene_dir=${parent_folder}/${gene}_2507
        python ${vritra_folder}summarize_contribution.py build_diamond_db \
        -g ${gene} \
        -o ${gene_dir}/4_finalized_database \
        -c ${gene_dir}/4_finalized_database/${gene}_core_representative_UniRef100.fas \
        -s ${gene_dir}/3_dataset_construction_refined/${gene}_sponge_UniRef90.fas \
        --uniprotkb-dir ${gene_dir}/2_dataset_construction_by_annotated_seqs_uniprotkb \
        -L ${gene_dir}/${gene}_construct_database_${date}.log
        """
        summarize_contribution.build_diamond_db.build_diamond_database(args.gene_prefix, args.core_rep_uniref100,
                                                                       args.sponge_fas_path, args.uniprotkb_dir,
                                                                       args.output_dir, logger)

    elif args.mode == "align":
        # two format indicate the sample ID and fastq file (by sample_table or by parameter input)
        if args.sample_table is not None:
            """
            Example: Provide sample-ID and path to fastq in a csv file, batch processing 
            sample1_ID,PATH/XXX_R1.fq:PATH/XXX_R2.fq
            """
            summarize_contribution.diamond_align.align_samples_from_csv(args.gene_prefix, args.sample_fastq,
                                                                        args.diamond_db, args.output_dir, args.thread,
                                                                        args.max_hit, args.identity_threshold,
                                                                        args.query_coverage, logger)
        elif (args.sample is not None) and (args.fastq is not None):
            """
            Example: Provide sample-ID and path to fastq, align one by one
            vritra_align = f"python {os.path.join(vritra_dir, 'summarize_contribution.py')} align " \
                       f"-g {gene_name} " \
                       f"--sample {srr_prefix} " \
                       f"--fastq {':'.join(input_fq_path_list)} " \
                       f"-d {db_path} " \
                       f"-o {gene_dir} " \
                       f"-L {logger_path}"            
            """
            fastq_path_list = args.fastq.split(":")
            summarize_contribution.diamond_align.align_sample_by_diamond(args.gene_prefix, args.sample, fastq_path_list,
                                                                         args.diamond_db, args.output_dir, args.thread,
                                                                         args.max_hit, args.identity_threshold,
                                                                         args.query_coverage, logger)
        else:
            print(f"Error! sample information is missing. Use -t or or '--sample and --fastq'")

    elif args.mode == "summarize":
        """
        Example: Summarize diamond report to count/CPM/RPKM
        
        vritra_dir = "/gpfs/data/lilab/home/zhoub03/Liisa_Beta_glucuronidase/Vritra_v2_20260319"
        output_folder = "/gpfs/data/lilab/home/zhoub03/Lama_oxalate/precision_medicine/processed_data/oxalate_gene_summary_improved_report_2602"
        frc_database_path = "/gpfs/data/lilab/home/zhoub03/generalized_pipeline_20240925/oxalate_gene_set_0729/FRC_2507/4_finalized_database/FRC_finalized_corres
pondence.csv"
        oxc_database_path = "/gpfs/data/lilab/home/zhoub03/generalized_pipeline_20240925/oxalate_gene_set_0729/OXC_2507/4_finalized_database/OXC_finalized_corres
pondence.csv"
        read_count_filename = "precision_medicine_MGX_read_count.tsv"
    dna_frc_summarize = f"python {os.path.join(vritra_dir, 'summarize_contribution.py')} " \
                        f"summarize " \
                        f"-g FRC " \
                        f"--read-count {read_count_filename} " \
                        f"--sample-fastq {os.path.join(output_folder, 'dna_sample_fq.csv')} " \
                        f"--sample-diamond {os.path.join(output_folder, 'dna_sample_diamond_FRC.csv')} " \
                        f"--tax-mapping {frc_database_path} " \
                        f"-o {output_folder} " \
                        f"-L dna_sample_vritra_summarize_frc_260324.log " \
                        f"--identity-threshold 80 " \
                        f"--len-threshold 45"
        """
        summarize_contribution.diamond_summarize.summarize_diamond_report(args.gene_prefix, args.read_count,
                                                                          args.sample_fastq, args.sample_diamond,
                                                                          args.tax_mapping, args.output_dir, logger,
                                                                          args.identity_threshold, args.len_threshold)

